### PR TITLE
New (V)iper (E)dit icon

### PR DESCRIPTION
**Pull request by ghost**
See the two icon styles at commit  0733531fef535494cb79c18c2ace3158ecc46b91 and b344dcd59015bfd323e022ca970928dab3a8da48

https://github.com/maks/viper-edit/issues/2

### CODE REVIEW

**Comment by maks** [comment]
Thank you very much for contributing this! I really like it!
Would you please be able to also include a SVG version to allow me to resize it for use on Google Play and any other required formats for the future.

**Comment by ghost** [comment]
> Thank you very much for contributing this! I really like it!
> Would you please be able to also include a SVG version to allow me to resize it for use on Google Play and any other required formats for the future.

I'm glad, but I only have the full size PNG version:
source

**Comment by maks** [comment]
Thank you again for the contribution, but unfortunately I won't be able to accept it without a SVG or Vector Drawable source file.

**Comment by ghost** [comment]
SVG: [ic_launcher.zip](https://github.com/maks/viper-edit/files/4321616/ic_launcher.zip)

**Comment by maks** [comment]
@mi69 that's brilliant, thank you again!

**Comment by maks** [comment]
@mi69 please let me know how you would like me to credit your contribution, otherwise I'll just use:  "github user mi69"

**Comment by ghost** [comment]
A link to https://github.com/mi69 is enough.

**Pull request merged**
